spring:
  application:
    name: api_repo_commit
  datasource:
    url: jdbc:mysql://localhost:3306/repo_commit
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false